#pragma once

#include "framework/Scene.h"
#include "framework/GameObject/Shapes.h"
#include "framework/GameObject/objects/ShapeObject.h"
#include "glad/glad.h"
#include "GLFW/glfw3.h"
#include "core/rendering/Window.h"
#include "core/rendering/Renderer.h"
#include "core/file/FileManagement.h"
#include "framework/Math.h"
#include "framework/input/KeyboardInput.h"
#include "framework/input/MouseInput.h"
#include "framework/Color.h"
#include "core/audio/Audio.h"
#include "framework/Game.h"