#pragma once
#include "framework/Scene.h"
#include "framework/GameObject/Shapes.h"
#include "framework/GameObject/objects/ShapeObject.h"
#include "glad/glad.h"
#include "GLFW/glfw3.h"
#include "core/Window.h"
#include "core/Renderer.h"
#include "core/file/FileManagement.h"
